### PR TITLE
feat: Support serialization using serde

### PR DESCRIPTION
**Pull request by slave5vw**
Serialization / deserialization using serde was added.

### CODE REVIEW

**Comment by jeffparsons** [comment]
Hi @slave5vw, thanks for the PR! :wave: 

I'd like to support JSON serialization using serde_json, and I think that won't work if we `#[derive(Serialize)]`, because the keys will be ranges, not strings. This is also a problem when serializing a BTreeMap directly, but in that case I think it's easier to justify expecting the user to pick a key type that's compatible with the target format -- with a RangeMap, the user doesn't have that choice.

Here's how I imagine serialization for rangemap:

- Strict control over the output format
    - This implies a manual implementation of Serialize and Deserialize, rather than using `#[derive(Serialize)]`, especially to avoid "leaking" implementation details like the `RangeStartWrapper` hack.
    - Format probably looks like a sequence of tuples `((key_start, key_end) value)`, which in JSON would end up as an array-of-arrays-of-arrays like `[[[0, 1], "Alice"], [[1, 2], "Bob"]]`
    - Unit-tested, so the format can't accidentally change based on internal details without someone explicitly acknowledging it.
- I don't care about performance for an initial implementation; e.g. I'd be fine if it was:
    - Serialize: dump all the values to a `Vec<((K, K), V)>`, and then delegate to the `Serialize` impl on that. (I _think_ that would probably give us the exact output we want anyway.)
    - Deserialize: parse all the values into the same type described above, and then insert them one-by-one into a new RangeMap (to ensure all invariants are upheld -- it's slower, but required to maintain API contract)
- Opt-in via `serde1` feature flag; I'd like to have 0 dependencies with default features if possible, just to be super-considerate to consumers of the crate.
- [Lower priority, but would still like] Avoid adding trait bounds anywhere they're not strictly required, e.g., on the struct itself or on impls that themselves don't require it. 

I know this makes it a bit bigger than what you "signed up for", but I'd be more than happy to help you work through it if you're interested. :grinning:

**Comment by slave5vw** [comment]
Thanks for feedback!

> I'd like to support JSON serialization using serde_json, and I think that won't work if we #[derive(Serialize)], because the keys will be ranges, not strings. This is also a problem when serializing a BTreeMap directly,

Well, as far as I know, serde supports serialization for range and BTreeMap. There were no problems with my limited testing. please note this. https://docs.serde.rs/serde/ser/index.html

However, since K type was limited to simple primitive types during testing, it seems that there may be other problems.
This PR is close to draft. Seeing again later, there's too much to be missed. I didn't consider inclusive_map and set ;)

**Comment by jeffparsons** [comment]
> Does it mean that range type and btreemap are not supported by serde? Well, as far as I know, serde supports serialization for range and BTreeMap. There were no problems with my limited testing. please note this. https://docs.serde.rs/serde/ser/index.html

Range and BTreeMap are fine separately, but you can't use a range as the key of a BTreeMap if you want to serialize it to JSON. (I.e. serde_json won't turn it into a string, and only string keys are allowed in JSON objects.)

**Comment by jeffparsons** [comment]
Closing in favor of https://github.com/jeffparsons/rangemap/pull/34

**Pull request closed without merging**
