### PR TITLE
improve gaps() time complexity for inclusive range map

### PR DESCRIPTION
**Pull request by neerajsi-msft**
I didn't initially realize that the inclusive range map is a completely different implementation. Implement an O(log n) initial seek for the inclusive range map, similar to abf6bec733a5e8939cf0d9a93f0f35ed7cee3de2.

### CODE REVIEW

**Comment by neerajsi-msft** [comment]
Hi Jeff,
Thanks for accepting my previous PR and leaving a suggestion to improve the inclusive range map.  Here's the requested change.

I was unable to run fuzz tests so far for this change and the previous change.  I'm developing on an aarch64 Windows machine and rustc doesn't yet support fuzzing for my target.  I'm currently installing WSL and giving fuzzing on Linux a try.  I'll drop another note here after I run the fuzz tests.

Thanks again for the very helpful library!.

**Comment by neerajsi-msft** [comment]
I tried out the two gaps fuzz targets for ~10 minutes each.  Looks like no issues found!

**Comment by neerajsi-msft** [comment]
This change is part of addressing issue #105.

**Comment by jeffparsons** [comment]
Thanks for this!

**Pull request merged**
